### ISSUE TITLE
Needs to filter messages to be unique.

### ISSUE THREAD

**Issue by Reprezent** [cfabian/JesusBot#5]
Single command multiple responses. This could be because discord does not guarantee only 1 message per  actual message in the server, its on the application to decipher them. Or it could be a loop in the program.

**Comment by Reprezent** [comment]
## Consistency
Discord operates at a scale where true consistency is impossible. Because of this, lots of operations in our API and in-between our services are eventually consistent. Due to this, client actions can never be serialized and may be executed in any order (if executed at all). Along with these constraints, events in Discord may:
* Never be sent to a client
* Be sent exactly one time to the client
* Be sent up to N times per client

Clients should operate on events and results from the API in as much of a idempotent behavior as possible.

Straight from the discord docs: https://discordapp.com/developers/docs/reference#consistency

**Comment by cfabian** [comment]
Are you talking about how the bot was responding to a command multiple times? If so that was an issue with the environment the bot was running on at the time and not an actually issue with the bot. I was accidentally running multiple instances of the bot at once.

If this is not what you are referring to could you please elaborate?
